device: cuda:1

model:
  name: DeepLabV3Plus
  yaml: /dgx/github/iSegmentation/iseg/models/deeplabv3plus/deeplabv3plus.yaml

augs:
  train:
    yaml: /dgx/github/iSegmentation/iseg/yamls/augs/train_augs.yaml
    updates:
  test:
    yaml: /dgx/github/iSegmentation/iseg/yamls/augs/test_augs.yaml
    updates:

dataset:
  name: CityscapeDataset
  base: /dgx/github/iSegmentation/data/cityscape
  train:
    query:
      - data_type == 'train'
  test:
    query:
      - data_type == 'val'

dataloader:
  train:
    args:
      batch_size: 16
      num_workers: 16
      shuffle: True
  test:
    args:
      batch_size: 1
      num_workers: 16
      shuffle: True

optimizer:
  name: Adam
  args:
    lr: 0.0002
    weight_decay: 0.00001

criterion:
  name: CrossEntropyLoss
  args:
    reduction: mean
    ignore_index: 255

run:
  train:
    epochs: 100
    use_amp: True

metrics:
  - name: iou
    args:
      num_classes: 19
      ignore_index: 255
